/*==================================================================

            pkgswchs.h

   GENERATED by procpkg.ndf

==================================================================*/

#define CORE
#define SYSTEM
#define V6AT
#define COMMAND
#define TIMEHOOK
#define DIRECTIO
#define PROFILE
#define USEROPS
